### ISSUE TITLE
Auto Set User Group on Authentik Users

### ISSUE THREAD

**Issue by DSMaVie** [QuITAC/authentik_docker#13]
This means, can be done in the user write stage according to the authentik docs.

**Comment by ghost** [comment]
So far, there have been no issues with users not being in the user group.

**Comment by NattCaat** [comment]
Immer noch keine Probleme. Am Wochenende, noch mal Brabra fragen

**Comment by ghost** [comment]
@Numifox findet es cool, dass in nextcloud alle in einer Gruppe sind
