### ISSUE TITLE
create user data self-management

### ISSUE THREAD

**Issue by DSMaVie** [QuITAC/authentik_docker#14]
authentik allows to set stages into so called executors. these can then be reached via url or a button on the authentik dashboard. there we can provide a user data self management, i.e. the users can self set their data, perhaps even memebership status? this could potentially be used for the vorstand to extract the emails of all members?

**Comment by NattCaat** [comment]
Bis auf Membership-Status klappt das. Vorstand fragen, in wie fern es praktisch ist, alle Mail-Addressen von Mitglieder mit diesem Feature zu bekommen.
