### ISSUE TITLE
Configure Reverse Proxy Headers

### ISSUE THREAD

**Issue by DSMaVie** [QuITAC/authentik_docker#3]
<https://goauthentik.io/docs/installation/reverse-proxy/>  states that we need the following Headers:
* X-Forwarded-Proto
* X-Forwarded-For
* Host
* Connection

we need to check how to do this with traefik

**Comment by DSMaVie** [comment]
Linked to https://github.com/QuITAC/proxy/issues/1 as they probably need to be set globally for all requests through the proxy.

**Comment by DSMaVie** [comment]
This was accidentally closed.

**Comment by mikitsu** [comment]
According to treafik's FAQ [1], `X-Forwarded-Proto` and `X-Forwarded-For` are set automatically. The `Connection` header is used for WebSockets, which should Just Work [2].

[1]: https://doc.traefik.io/traefik/getting-started/faq/#what-are-the-forwarded-headers-when-proxying-http-requests
[2]: https://stackoverflow.com/questions/46313356/how-to-proxy-websockets-in-traefik/46316349#46316349
